services:
  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: mortech_saldo
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    restart: always

  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
    - "80:80"
    volumes:
    - ./www:/var/www/html
    links:
      - mysql
